<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCcX22Dc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCcX22Dc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCcX22Dc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCcX22Dc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCcX22Dc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CcX22Dc',
    'container.build_id' => '0bcf8e4c',
    'container.build_time' => 1624750918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCcX22Dc');
