<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmQDIP4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmQDIP4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMmQDIP4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMmQDIP4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMmQDIP4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MmQDIP4',
    'container.build_id' => 'dbda85c5',
    'container.build_time' => 1624623411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmQDIP4');
