<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNFslfO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNFslfO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNFslfO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNFslfO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCNFslfO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CNFslfO',
    'container.build_id' => '00f1b9a9',
    'container.build_time' => 1627397971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNFslfO');
