<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErCqYpk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErCqYpk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErCqYpk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErCqYpk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerErCqYpk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ErCqYpk',
    'container.build_id' => '301eb622',
    'container.build_time' => 1625651677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErCqYpk');
